image: solvcon/solvcon_build:latest

stages:
  - build
  - test

before_script:
  - which g++; g++ --version
  - which python3; python3 --version

libmarch:opt:
  stage: build
  script:
    - mkdir -p ${CI_PROJECT_DIR}/libmarch/build/opt
    - cd ${CI_PROJECT_DIR}/libmarch/build/opt
    - cmake -DPYTHON_EXECUTABLE:FILEPATH=`which python3`
      -DCMAKE_BUILD_TYPE=Release
      -DTESTFILTER="*"
      ${CI_PROJECT_DIR}/libmarch
    - make -C ${CI_PROJECT_DIR}/libmarch/build/opt VERBOSE=1
    - make -C ${CI_PROJECT_DIR}/libmarch/build/opt run_gtest VERBOSE=1

libmarch:dbg:
  stage: build
  script:
    - mkdir -p ${CI_PROJECT_DIR}/libmarch/build/dbg
    - cd ${CI_PROJECT_DIR}/libmarch/build/dbg
    - cmake -DPYTHON_EXECUTABLE:FILEPATH=`which python3`
      -DCMAKE_BUILD_TYPE=Debug
      -DTESTFILTER="*"
      ${CI_PROJECT_DIR}/libmarch
    - make -C ${CI_PROJECT_DIR}/libmarch/build/dbg VERBOSE=1
    - make -C ${CI_PROJECT_DIR}/libmarch/build/dbg run_gtest VERBOSE=1

solvcon:opt:
  stage: build
  script:
    - make VERBOSE=1
    - nosetests3 --with-doctest -v
  artifacts:
    untracked: true

solvcon:opt:test:gasplus:
  dependencies:
    - solvcon:opt
  stage: test
  script:
    - nosetests3 ftests/gasplus/* -v

solvcon:opt:test:parallel:
  dependencies:
    - solvcon:opt
  stage: test
  script:
    - nosetests3 ftests/parallel/* -v

solvcon:package:
  stage: build
  script:
    - make SC_PURE_PYTHON=1 package
    - make SC_PURE_PYTHON=1 build_from_package
    - make VERBOSE=1 SC_PURE_PYTHON=1 test_from_package
  artifacts:
    paths:
      - dist/SOLVCON*.tar.gz
