image: solvcon/solvcon_build:latest

before_script:
- which g++; g++ --version
- which python3; python3 --version

libmarch_opt_build:
  script:
  - mkdir -p ${CI_PROJECT_DIR}/libmarch/build/rel
  - cd ${CI_PROJECT_DIR}/libmarch/build/rel
  - cmake -DPYTHON_EXECUTABLE:FILEPATH=`which python3`
    -DCMAKE_BUILD_TYPE=Release
    -DTESTFILTER="*"
    ${CI_PROJECT_DIR}/libmarch
  - cd ${CI_PROJECT_DIR}/libmarch
  - make -C build/rel run_gtest VERBOSE=1

libmarch_dbg_build:
  script:
  - mkdir -p ${CI_PROJECT_DIR}/libmarch/build/dbg
  - cd ${CI_PROJECT_DIR}/libmarch/build/dbg
  - cmake -DPYTHON_EXECUTABLE:FILEPATH=`which python3`
    -DCMAKE_BUILD_TYPE=Debug
    -DTESTFILTER="*"
    ${CI_PROJECT_DIR}/libmarch
  - cd ${CI_PROJECT_DIR}/libmarch
  - make -C build/dbg run_gtest VERBOSE=1
