cache:
  directory:
  - $HOME/miniconda

# If using C++11/14 see http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
addons:
  apt:
    packages:
      - openssh-client
      - openssh-server
      - liblapack-pic
      - liblapack-dev

env:
  global:
    # Disable GCE boto plugin which is incompatible to Python 3, see
    # https://github.com/travis-ci/travis-ci/issues/5246
    - BOTO_CONFIG=/tmp/nowhere

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: cpp
      compiler: gcc
    - os: osx
      #osx_image: xcode7.3
      language: cpp
      compiler: clang

before_install:
  # Configure ssh
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  # Install minimal conda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - which python; python --version
  - conda info -a
  # Debug information of compiler
  - which $CXX; $CXX --version
  - which $CC; $CC --version

install:
  - ${TRAVIS_BUILD_DIR}/contrib/devenv/create.sh
  - source ${TRAVIS_BUILD_DIR}/build/env/start
  - ${TRAVIS_BUILD_DIR}/contrib/conda.sh
  - ${TRAVIS_BUILD_DIR}/contrib/build-pybind11-in-conda.sh
  - which python; python --version
  - conda info -a
  - set | grep SC
  - set | grep CONDA

script:
  # C++ debug build
  - mkdir -p ${TRAVIS_BUILD_DIR}/build/debug
  - cd ${TRAVIS_BUILD_DIR}/build/debug
  - cmake -DPYTHON_EXECUTABLE:FILEPATH=`which python` -Dpybind11_DIR=${CONDA_PREFIX}/share/cmake/pybind11 -DTESTFILTER="*" -DCMAKE_BUILD_TYPE=Debug ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}
  - make -C build/debug run_gtest VERBOSE=1
  # Package
  - cd ${TRAVIS_BUILD_DIR}
  - contrib/release.sh
