package:
  name: gmsh
  version: "3.0.6"

source:
  fn: gmsh-3.0.6-source.tgz
  url: http://gmsh.info//src/gmsh-3.0.6-source.tgz
  md5: 78bbfdd695b29cfef18a99f93226afc5

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cmake
    - gmp
  run:
    - python
    - numpy
    - gmp

test:
  commands:
    - gmsh -help

about:
  home: http://geuz.org/gmsh/
  license: GPL
  summary: A three-dimensional finite element mesh generator with built-in pre- and post-processing facilities
